// Writes the account console's palette from @gryt/ui's own token file: the console is static
// files, not a build, so it needs plain custom properties. Re-run after bumping @gryt/ui.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const src = fileURLToPath(new URL("../node_modules/@gryt/ui/dist/theme.css", import.meta.url));
const out = fileURLToPath(new URL("../../themes/gryt/account/resources/css/tokens.css", import.meta.url));

const theme = readFileSync(src, "utf8");

// Only the colours. The spring curve and the font stack are for components
// this console does not have, and shipping them would suggest otherwise.
const tokens = [...theme.matchAll(/--color-(gryt-[a-z-]+):\s*([^;]+);/g)].map(
  ([, name, value]) => `  --${name}: ${value.trim()};`,
);

if (tokens.length === 0) {
  throw new Error(`No --color-gryt-* tokens in ${src}. Did @gryt/ui change shape?`);
}

writeFileSync(
  out,
  [
    "/* Generated by login-theme/scripts/account-tokens.mjs — do not edit.",
    " *",
    " * The source is @gryt/ui/theme.css. Re-run `npm run account-tokens` in",
    " * login-theme/ after bumping @gryt/ui and commit the result.",
    " */",
    ":root {",
    ...tokens,
    "}",
    "",
  ].join("\n"),
);

console.log(`account-tokens: wrote ${tokens.length} colours to ${out}`);
