// Writes the account console's palette from @gryt/ui's own token file: the console is static
// files, not a build, so it needs plain custom properties. Re-run after bumping @gryt/ui.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const src = fileURLToPath(new URL("../node_modules/@gryt/ui/dist/theme.css", import.meta.url));
const out = fileURLToPath(new URL("../../themes/gryt/account/resources/css/tokens.css", import.meta.url));

const theme = readFileSync(src, "utf8");

// Only the colours. The spring curve and the font stack are for components this console
// does not have, and shipping them would suggest otherwise.

// [a-z0-9-] and not [a-z-]: 0.29 moved to numbered scales, so the semantic names are
// aliases now and without the digits every colour in the generated file resolves to nothing.
const tokens = [...theme.matchAll(/--color-(gryt-[a-z0-9-]+):\s*([^;]+);/g)].map(
  ([, name, value]) => `  --${name}: ${value.trim()};`,
);

if (tokens.length === 0) {
  throw new Error(`No --color-gryt-* tokens in ${src}. Did @gryt/ui change shape?`);
}

// Every var() needs a definition in the same file, or the console renders with no colour.
// verify does not look at the account theme and the check above only fires on zero tokens.
const defined = new Set(tokens.map((t) => t.match(/--([a-z0-9-]+):/)[1]));
const missing = [
  ...new Set(
    tokens.flatMap((t) => [...t.matchAll(/var\(--([a-z0-9-]+)\)/g)].map((m) => m[1])),
  ),
].filter((name) => !defined.has(name));

if (missing.length > 0) {
  throw new Error(
    `${missing.length} token(s) referenced but not defined: ${missing.join(", ")}. ` +
      `Did @gryt/ui change the shape of its token file?`,
  );
}

writeFileSync(
  out,
  [
    "/* Generated by login-theme/scripts/account-tokens.mjs — do not edit.",
    " *",
    " * The source is @gryt/ui/theme.css. Re-run `npm run account-tokens` in",
    " * login-theme/ after bumping @gryt/ui and commit the result.",
    " */",
    ":root {",
    ...tokens,
    "}",
    "",
  ].join("\n"),
);

console.log(`account-tokens: wrote ${tokens.length} colours to ${out}`);
