// Writes the account console's palette from @gryt/ui's own token file.
//
// `@gryt/ui/theme.css` ships the tokens in Tailwind's `@theme` form, which a
// browser ignores — it is meant to be imported into a Tailwind entry, and the
// login theme consumes it that way. The account console is not a build, it is
// a directory of static files Keycloak serves, so it needs the same values as
// plain custom properties.
//
// Generated rather than copied, because a copy is a second palette that drifts
// the first time somebody tunes a colour. Run `npm run account-tokens` after
// bumping @gryt/ui and commit what changes.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const src = fileURLToPath(new URL("../node_modules/@gryt/ui/dist/theme.css", import.meta.url));
const out = fileURLToPath(new URL("../../themes/gryt/account/resources/css/tokens.css", import.meta.url));

const theme = readFileSync(src, "utf8");

// Only the colours. The spring curve and the font stack are for components
// this console does not have, and shipping them would suggest otherwise.
const tokens = [...theme.matchAll(/--color-(gryt-[a-z-]+):\s*([^;]+);/g)].map(
  ([, name, value]) => `  --${name}: ${value.trim()};`,
);

if (tokens.length === 0) {
  throw new Error(`No --color-gryt-* tokens in ${src}. Did @gryt/ui change shape?`);
}

writeFileSync(
  out,
  [
    "/* Generated by login-theme/scripts/account-tokens.mjs — do not edit.",
    " *",
    " * The source is @gryt/ui/theme.css. Re-run `npm run account-tokens` in",
    " * login-theme/ after bumping @gryt/ui and commit the result.",
    " */",
    ":root {",
    ...tokens,
    "}",
    "",
  ].join("\n"),
);

console.log(`account-tokens: wrote ${tokens.length} colours to ${out}`);
