// Writes the admin console's palette from @gryt/theme's Gryt preset — the same colours the
// account console gets from @gryt/ui, by a route where the preset is one line to change.

// It was the OLED preset first. It should not be: the point of theming the console at all
// is that Gryt's console looks like Gryt, not that it looks like a different room.

// The three on-* values differ from the account theme's — #0c0a20 against #141126 and so
// on. Drift, not a decision: login-theme pins @gryt/ui 0.4.0 against 0.29.0 (GRYT-1090).

// Re-run `npm run admin-tokens` after bumping @gryt/theme and commit the result.

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

import { grytPresets } from "@gryt/theme";

const PRESET = "gryt";
const out = fileURLToPath(
  new URL("../../themes/gryt/admin/resources/css/tokens.css", import.meta.url),
);

const preset = grytPresets.find((p) => p.id === PRESET);
if (!preset) {
  const ids = grytPresets.map((p) => p.id).join(", ");
  throw new Error(`No "${PRESET}" preset in @gryt/theme. Available: ${ids}`);
}

const { hue, dark } = preset.theme;

// Same names the account theme uses, so admin.css and account.css can share the
// shape of their remap and only differ in what the values are.
const tokens = {
  "gryt-bg": dark.bg,
  "gryt-surface": dark.surface,
  "gryt-surface-raised": dark.surfaceRaised,
  "gryt-surface-hover": dark.surfaceHover,
  "gryt-border": dark.border,
  "gryt-text": dark.text,
  "gryt-muted": dark.muted,
  "gryt-accent": hue.accent,
  "gryt-accent-light": hue.accentLight,
  "gryt-secondary": hue.secondary,
  "gryt-secondary-light": hue.secondaryLight,
  "gryt-success": hue.success,
  "gryt-danger": hue.danger,
  "gryt-danger-light": hue.dangerLight,
  "gryt-warning": hue.warning,
  "gryt-on-accent": hue.onAccent,
  "gryt-on-secondary": hue.onSecondary,
  "gryt-on-danger": hue.onDanger,
};

const missing = Object.entries(tokens).filter(([, v]) => !v);
if (missing.length) {
  throw new Error(
    `Preset "${PRESET}" is missing: ${missing.map(([k]) => k).join(", ")}. Did @gryt/theme change shape?`,
  );
}

const body = Object.entries(tokens)
  .map(([name, value]) => `  --${name}: ${value};`)
  .join("\n");

writeFileSync(
  out,
  `/* Generated by login-theme/scripts/admin-tokens.mjs — do not edit.
 *
 * The source is the "${preset.id}" preset in @gryt/theme: ${preset.note}
 * Re-run \`npm run admin-tokens\` after bumping @gryt/theme and commit the result.
 */
:root {
${body}
}
`,
);

console.log(`Wrote ${Object.keys(tokens).length} tokens from "${preset.id}" to ${out}`);
