// Writes the admin console's palette from @gryt/theme's Gryt preset.
//
// The account console takes its palette from @gryt/ui's own token file. This
// reads the same palette from @gryt/theme's preset list instead, which is the
// same values by a shorter route and makes the choice of preset one line rather
// than a rewrite (GRYT-1089).
//
// It was the OLED preset first, on the theory that the admin console should look
// like a different room. It should not: the point of theming it at all is that
// Gryt's console looks like Gryt.
//
// The three `on-*` values here differ slightly from the account theme's, which
// come from @gryt/ui: #0c0a20 against #141126 for on-accent, and similar for the
// other two. That is not a decision, it is drift — login-theme pins @gryt/ui
// 0.4.0 against npm's 0.29.0 (GRYT-1090), so the account tokens are months old
// and these are current. Both are "the Gryt palette"; they will agree again once
// that bump lands.
//
// Re-run `npm run admin-tokens` after bumping @gryt/theme and commit the result.
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

import { grytPresets } from "@gryt/theme";

const PRESET = "gryt";
const out = fileURLToPath(
  new URL("../../themes/gryt/admin/resources/css/tokens.css", import.meta.url),
);

const preset = grytPresets.find((p) => p.id === PRESET);
if (!preset) {
  const ids = grytPresets.map((p) => p.id).join(", ");
  throw new Error(`No "${PRESET}" preset in @gryt/theme. Available: ${ids}`);
}

const { hue, dark } = preset.theme;

// Same names the account theme uses, so admin.css and account.css can share the
// shape of their remap and only differ in what the values are.
const tokens = {
  "gryt-bg": dark.bg,
  "gryt-surface": dark.surface,
  "gryt-surface-raised": dark.surfaceRaised,
  "gryt-surface-hover": dark.surfaceHover,
  "gryt-border": dark.border,
  "gryt-text": dark.text,
  "gryt-muted": dark.muted,
  "gryt-accent": hue.accent,
  "gryt-accent-light": hue.accentLight,
  "gryt-secondary": hue.secondary,
  "gryt-secondary-light": hue.secondaryLight,
  "gryt-success": hue.success,
  "gryt-danger": hue.danger,
  "gryt-danger-light": hue.dangerLight,
  "gryt-warning": hue.warning,
  "gryt-on-accent": hue.onAccent,
  "gryt-on-secondary": hue.onSecondary,
  "gryt-on-danger": hue.onDanger,
};

const missing = Object.entries(tokens).filter(([, v]) => !v);
if (missing.length) {
  throw new Error(
    `Preset "${PRESET}" is missing: ${missing.map(([k]) => k).join(", ")}. Did @gryt/theme change shape?`,
  );
}

const body = Object.entries(tokens)
  .map(([name, value]) => `  --${name}: ${value};`)
  .join("\n");

writeFileSync(
  out,
  `/* Generated by login-theme/scripts/admin-tokens.mjs — do not edit.
 *
 * The source is the "${preset.id}" preset in @gryt/theme: ${preset.note}
 * Re-run \`npm run admin-tokens\` after bumping @gryt/theme and commit the result.
 */
:root {
${body}
}
`,
);

console.log(`Wrote ${Object.keys(tokens).length} tokens from "${preset.id}" to ${out}`);
